#!/bin/sh

set -e

go mod tidy
go build -ldflags='-s -w' -o "./dist/fzg" -- "./cmd/fzg/main.go"

mkdir -pv -- "$HOME/.local/bin"
cp -av -- "./dist/fzg" "$HOME/.local/bin/fzg"

mkdir -pv -- "$HOME/.config/fzg"
cp -av -- ./configs/fzg.yaml "$HOME/.config/fzg"
cp -av -- ./shell/completions.bash "$HOME/.config/fzg"
